// ==========================Dessert recipies==========================
const dessertrecipes = {
  "three-milk-cake": {
    title: "Three Milk Cake",
    ingredients: [
      "Anda (Egg) 1",
      "Bareek Cheeni (Caster sugar) 1/3 Cup",
      "Vanilla Essence 1 tsp",
      "Cooking oil ¼ Cup",
      "Maida (All-purpose flour) 1 Cup",
      "Cocoa powder ¼ Cup",
      "Namak (Salt) ½ tsp",
      "Baking powder 1 tsp",
      "Doodh (Milk) ¼ Cup",
      "Milk chocolate chopped 3 tbs",
      "Doodh (Milk) hot 1 Cup",
      "Instant coffee 1 tsp",
      "Condensed milk 1/3 Cup",
      "Chocolate whipped cream",
      "Chocolate shavings",
    ],
    steps: [
      "In a bowl, add egg, caster sugar, vanilla essence & whisk well.",
      "Add cooking oil & whisk well.",
      "On a bowl, place sifter, add all-purpose flour, cocoa powder, salt, baking powder & sift together then mix well.",
      "Add milk & whisk well.",
      "Grease 8-inch nonstick frying pan with cooking oil & pour prepared batter.",
      "Preheat heat diffuser plate or griddle (tawa), place frying pan over heat diffuser plate, cover with lid & kitchen cloth then cook on low flame until skewer comes out clean (10-11 minutes).",
      "Let it cool completely.",
      "Carefully remove cake from frying pan & poke holes with help of chopstick.",
      "In a jug, add chocolate, hot milk, instant coffee & mix well until chocolate melts.",
      "Add condensed milk & mix well.",
      "Slowly pour prepared milk syrup over the top of the cake, filling holes, cover & refrigerate for 30 minutes.",
      "Garnish with chocolate whipped cream, chocolate shavings & serve!",
    ],
  },
  "angoori-rasmalai": {
    title: "Angoori Rasmalai",
    ingredients: [
      "Olpers Milk powder ½ Cup",
      "Maida (All-purpose flour) 1 tbs",
      "Baking powder ½ tsp",
      "Ghee (Clarified butter) 1 tbs",
      "Anda (Egg) whisked 3-4 tbs",
      "Doodh (Milk) 1 litre",
      "Sugar ½ Cup or to taste",
      "Zafran (Saffron strands) ½ tsp dissolved in 2 tbs of milk",
      "Kewra essence ½ tsp",
      "Elaichi ke Danay (Cardamom seeds) crushed ½ tsp",
      "Pista (Pistachios) sliced 1 tbs",
      "Badam (Almonds) sliced 1 tbs",
      "Badam (Almonds) sliced",
      "Pista (Pistachios) sliced",
    ],
    steps: [
      "In a bowl, add milk powder, all-purpose flour, baking powder & mix well.",
      "Add clarified butter, gradually add whisked egg (add 3 tbs & mix well, add 1 more tbs if required), mix well & gather the dough (don’t over mix).",
      "With the help of greased hands, take small quantity of mixture (5g) make smooth balls with no cracks (makes 30).",
      "In a wok, add milk, bring it to boil & cook on low flame for 8-10 minutes.",
      "Add sugar, dissolved saffron, kewra essence, cardamom seeds, mix well & cook on low flame for 2-3 minutes.",
      "In boiling milk, add prepared balls & cook on very low flame until they float on the surface & increase in size (don’t stir), cover & cook on low flame for 10 minutes.",
      "Turn off the flame, add pistachios & almonds.",
      "Let it cool completely.",
      "Garnish with almonds, pistachios & serve!",
    ],
  },
  "barfi-rolls": {
    title: "Barfi Rolls",
    ingredients: [
      "Ghee (Clarified butter) 3 tbs",
      "Olpers Milk ¾ Cup",
      "Sugar powdered 4-5 tbs or to taste",
      "Olpers Milk powder 2 Cups",
      "Khopra (Desiccated coconut) 1 tbs",
      "Elaichi powder (Cardamom powder) ½ tsp",
      "Chandi ka warq (Edible silver leaf)",
      "Pista (Pistachios) sliced",
    ],
    steps: [
      "In a non-stick wok, add clarified butter, milk, sugar & milk powder.",
      "Turn on the flame, mix well & cook on low flame until it leaves the sides of pot (6-8 minutes).",
      "Add desiccated coconut, cardamom powder, mix well & cook on low flame for 4-5 minutes or until soft dough is formed.",
      "Transfer the mixture on a flat working surface, wrap in a cling film & refrigerate for 10 minutes until cool down.",
      "Take 20g of mixture & make an oval shape barfi.",
      "Decorate with edible silver leaf, pistachios & serve (makes 22).",
    ],
  },
  "chocolate-donuts": {
    title: "Chocolate Donuts",
    ingredients: [
      "Khameer (Instant yeast) 2 & ½ tsp",
      "Bareek cheeni (Caster sugar) 1 tsp",
      "Warm milk ¾ Cup",
      "Instant coffee 1 tbs",
      "Sunridge Maida (All-purpose flour) 1 Cup",
      "Cocoa powder ¼ Cup",
      "Namak (Salt) ½ tsp",
      "Bareek cheeni (Caster sugar) 1/3 Cup",
      "Makhan (Butter) melted 3 tbs",
      "Anda (Egg) 1",
      "Vanilla essence 1 tsp",
      "Sunridge Maida (All-purpose flour) sifted 1 Cup",
      "Sunridge Maida (All-purpose flour) 2 tbs",
      "Cooking oil 1 tsp",
      "Cooking oil for frying",
      "White chocolate grated 150g",
      "Cream 2-3 tbs",
      "Milk chocolate grated 150g",
      "Cream 2-3 tbs",
      "Multi color sprinkles",
      "Caramel biscuits crumbled",
      "Desiccated coconut",
    ],
    steps: [
      "In a small jug, add instant yeast, caster sugar, milk and mix well, cover & let it rest for 10-15 minutes.",
      "On a bowl, place a sifter, add instant coffee & sift it.",
      "Add all-purpose flour, cocoa powder, salt & sift together then mix well.",
      "Add caster sugar & mix well.",
      "Now add dissolved yeast mixture, melted butter, egg, vanilla essence & mix until well combined.",
      "Add all-purpose flour & mix well.",
      "Add all-purpose flour & knead until dough is formed.",
      "Grease with cooking oil (1 tsp), cover & let it proof for 1 hour (warm place).",
      "Knead dough again until smooth, sprinkle dry flour and take out a small dough (50g each), make a ball, sprinkle all-purpose flour & roll out with the help of rolling pin.",
      "Coat a small cutter with all-purpose flour and cut with a floured cutter from the center and similarly make other donuts.",
      "Cover with kitchen towel & let it proof for 15-20 minutes.",
      "In a wok, heat cooking oil & fry donuts on low flame from both sides until done.",
      "Let them cool.",
      "In a bowl, add white chocolate, cream & microwave for 30 seconds or until chocolate melts (mix in between) then whisk well until smooth.",
      "Now dip one side of prepared donuts in it.",
      "Place it on wire rack and drizzle melted white chocolate.",
      "In a bowl, add milk chocolate, cream & microwave for 30 seconds or until chocolate melts (mix in between) then whisk well until smooth.",
      "Now dip one side of prepared donuts in it.",
      "Place it on wire rack and drizzle melted milk chocolate.",
      "Decorate donuts with multi color sprinkles, biscuits crumbles and desiccated coconuts (makes 16 Donuts).",
      "Place onto a wire rack & serve!",
    ],
  },
  "swirll-brownies": {
    title: "Swirll Brownies",
    ingredients: [
      "Cream cheese 1/2 Cup",
      "Anday ki zardi (Egg yolk) 1",
      "Maida (All-purpose flour) 1 tbs",
      "Vanilla essence 1/2 tsp",
      "Pissi hoye cheeni (Powdered sugar) 1/4 Cup",
      "Maida (All-purpose flour) sifted 1/2 Cup",
      "Cocoa powder 1/3 Cup",
      "Namak (Salt) 1/2 tsp",
      "Cheeni (Sugar) 3/4 Cup",
      "Anday (Eggs) 2",
      "Vanilla essence 1 tsp",
      "Makhan (Butter) melted 100 gms",
      "Chocolate chips as required",
    ],
    steps: [
      "In a bowl, add cream cheese, egg yolk, all-purpose flour, vanilla essence, powdered sugar and mix until well combined & set aside.",
      "In bowl, add all-purpose flour, cocoa powder, salt, mix well & set aside.",
      "In grinder, add sugar and grind to make a fine powder & set aside.",
      "In bowl, add eggs, powdered sugar, vanilla essence, melted butter and whisk well.",
      "Now add dry flour mixture and mix with the help of the spatula.",
      "In 8 x 8 inch baking pan lined with butter paper, add prepared brownie batter and cream cheese batter and make swirls with the help of the skewer.",
      "Sprinkle chocolate chips and bake in preheated oven at 170 C for 18-20 minutes.",
    ],
  },
  "achari-waffles": {
    title: "Achari Waffles",
    ingredients: [
      "Chicken boneless cubes 300 gms",
      "Shan chicken tikka masala 1 tbs",
      "Dahi (Yogurt) whisked 2 tbs",
      "Cooking oil 1 tbs",
      "Cooking oil 1 tsp",
      "Pyaz (Onion) cubes ½ Cup",
      "Shimla mirch (Capsicum) cubes ½ Cup",
      "Makhan (Butter) 1 tbs",
      "Maida (All-purpose flour) 1 & ½ tbs",
      "Doodh (Milk) 1 Cup",
      "Cheddar cheese grated 1/4 Cup",
      "Namak (Salt) 1/4 tsp or to taste",
      "Lal mirch powder (Red chili powder) ½ tsp or to taste",
      "Chicken powder 1 tsp",
      "Makhan (Butter) 2 tbs",
      "Pyaz (Onion) chopped 1 medium",
      "Lehsan (Garlic) crushed 1 tbs",
      "Aloo (Potatoes) boiled ½ kg",
      "Baking powder 1 tsp",
      "Shan achar gosht masala 1 tbs",
      "Maida (All-purpose flour) sifted 1/4 Cup",
      "Anday (Eggs) 2",
      "Hara pyaz (Green onion) leaves",
    ],
    steps: [
      "In bowl, add chicken, chicken tikka masala, yogurt, mix well and marinate for 15 minutes.",
      "In frying pan, add cooking oil, marinated chicken and cook until chicken is done (approx. 12-15 minutes).",
      "In the center of the frying pan, add cooking oil, onion, capsicum and stir fry for 1 minute then add chicken, mix well & set aside.",
      "In saucepan, add butter and let it melt.",
      "Add all-purpose flour and mix well for 1 minute.",
      "Add milk and whisk well.",
      "Add cheddar cheese, salt, red chili powder, chicken powder, whisk continuously and cook until sauce thickens & set aside.",
      "In frying pan, add butter and let it melt.",
      "Add onion, garlic, mix well and sauté until translucent & set aside.",
      "In bowl, add potatoes and mash well with the help of the masher.",
      "Now add sautéed onion+garlic, baking powder, achar gosht masala, all-purpose flour, eggs and mix until well combined.",
      "Preheat waffle maker and grease with oil, add prepared batter on waffle iron and spread evenly.",
      "Cook for 8-10 minutes (makes 5-6).",
      "On serving plate, place waffle, cooked chicken, drizzle white sauce and garnish with green onion leaves & serve!",
    ],
  },
  "mango-loaf-cake": {
    title: "Mango Loaf Cake",
    ingredients: [
      "Aam (Mango) chunks 1 & ½ Cup",
      "Doodh (Milk) ½ Cup",
      "Sirka (Vinegar) 1 tbs",
      "Maida (All-purpose flour) 1 & ½ Cup",
      "Cornflour 2 tbs",
      "Baking powder 1 tsp",
      "Baking soda ½ tsp",
      "Himalayan pink salt ¼ tsp",
      "Cooking oil 1/3 Cup",
      "Bareek cheeni (Caster sugar) ¾ Cup",
      "Vanilla essence 1 tsp",
      "Maida (All-purpose flour)",
      "Icing sugar ½ Cup",
      "Doodh (Milk) 1 & ½ tbs",
      "Vanilla essence ½ tsp",
    ],
    steps: [
      "In a blending jug, add mango chunks & blend well to make a puree (1 cup) & set aside.",
      "In milk, add vinegar, mix well & let it rest for 10 minutes. Buttermilk is ready!",
      "On a bowl, place a strainer, add all-purpose flour, cornflour, baking powder, baking soda & pink salt, sift together, mix well & set aside.",
      "In another bowl, add cooking oil, buttermilk, mango puree (1 cup), caster sugar, vanilla essence & whisk until sugar is dissolved.",
      "Add dry ingredients, fold gently & whisk well until smooth.",
      "On greased 7x3 inches loaf pan lined with butter paper, pour prepared batter & tap few times.",
      "Coat a dough cutter with all-purpose flour & dip its tip in the center of cake batter to make a line.",
      "Bake in preheated oven at 180C for 55-60 minutes or until skewer comes out clean (convection mode).",
      "Let it cool for 10 minutes.",
      "In a bowl, add icing sugar, milk, vanilla essence & whisk until well combined & transfer to a piping bag.",
      "Drizzle prepared sugar glaze on cake, cut into slices & serve!",
    ],
  },
  "oreo-cream-cups": {
    title: "Oreo Cream Cups",
    ingredients: [
      "Oreo biscuits 300g",
      "Makhan (Butter) melted 50g",
      "Olpers cream chilled 300ml",
      "Vanilla essence ½ tsp",
      "Icing sugar 3-4 tbs or to taste",
      "Cream cheese 100ml",
      "Milk chocolate chopped 80g",
      "Olpers cream 50ml (room temperature)",
      "Oreo biscuit",
    ],
    steps: [
      "Remove Oreo cream from Oreo biscuits & reserve for later use.",
      "In a chopper, add Oreo biscuits & chop well.",
      "Take out ½ cup of Oreo crumbs & reserve for later use. In remaining Oreo crumbs, add butter, chop well & set aside.",
      "In a large bowl, add ice cubes & place another bowl over it, add cream, vanilla essence, icing sugar & beat well until soft peaks form.",
      "Add reserved Oreo cream, cream cheese & beat well.",
      "Add reserved Oreo crumbs (1/2 Cup), fold gently until combined & transfer to a piping bag.",
      "In a bowl, add milk chocolate, cream & microwave for 1 minute then mix until well smooth & transfer to a piping bag.",
      "In serving cup, add 2-3 tbs of Oreo crumbs & press firmly to set an even layer.",
      "Pipe out prepared Oreo cream, garnish with prepared ganache & Oreo biscuits.",
      "Serve chilled (makes 6)!",
    ],
  },
  "creamy-cupcakes": {
    title: "Creamy Cupcakes",
    ingredients: [
      "Maida (All-purpose flour) 1 & ½ Cup",
      "Instant coffee 1 tsp",
      "Cocoa powder ½ Cup",
      "Baking soda 1 tsp",
      "Baking powder ½ tsp",
      "Namak (Salt) ½ tsp",
      "Equal Sucralose 1/3 Cup",
      "Doodh (Milk) 1 & ¼ Cup (room temperature)",
      "Cooking oil ½ Cup",
      "Anday (Eggs) 2 (room temperature)",
      "Vanilla essence 1 tsp",
      "Makhan (Butter) soft 120g",
      "Equal Sucralose 1/3 Cup",
      "Doodh (Milk) 1 tsp (room temperature)",
      "Coconut essence ¼ tsp",
      "Khopra (Desiccated coconut) roasted",
    ],
    steps: [
      "In a bowl, place a sifter, add all-purpose flour, instant coffee, cocoa powder, baking soda, baking powder, salt & sift together.",
      "Add equal sucralose, mix well & set aside.",
      "In another bowl, add milk, cooking oil, eggs, vanilla essence & beat well.",
      "Gradually add dry ingredients & beat until well combined.",
      "On a cupcakes tray, place cupcake linings & add 2 tbs of prepared batter.",
      "Bake in preheated oven at 180C for 15 minutes.",
      "Take out cupcakes from oven & let it cool (makes 12).",
      "In a bowl, add butter & beat until changes color.",
      "Add equal sucralose & beat for a minute.",
      "Add milk & beat well.",
      "Add coconut essence, beat well then transfer into piping bag & refrigerate until use.",
      "Remove cupcakes from muffin tray, pipe the coconut frosting over cupcakes & sprinkle roasted desiccated coconut & serve!",
    ],
  },
  "til-gur-laddu": {
    title: "Til Gur Laddu",
    ingredients: [
      "Til (Sesame seeds) 250g",
      "Ghee (Clarified butter) 1 tbs",
      "Gur (Jaggery) 250g",
    ],
    steps: [
      "In a wok, add sesame seeds, dry roast until fragrant & set aside.",
      "In the same wok, add clarified butter & let it melt.",
      "Add jaggery, mix well & cook until it turns thick & foamy (6-8 minutes).",
      "To check if syrup is ready, pour few drops in water if they dissolve, it’s ready to use.",
      "Add roasted sesame seeds & mix well.",
      "Let it cool for 5 minutes.",
      "With the help of greased hands & spoon, take small quantity of mixture (16g) & make balls of equal sizes (makes 30).",
      "Let them cool completely & store ladoos in airtight jar or container.",
    ],
  },
};
// ==========================Dessert recipies==========================
// ==========================Breakfast recipies==========================
const breakfastrecipes = {
  "anda-ghotala": {
    title: "Anda Ghotala",
    ingredients: [
      "Anday (Eggs) - 6",
      "Oil - ¼ Cup",
      "Pyaz (Onion), chopped - 2 medium",
      "Zeera (Cumin seeds) - 1 tsp",
      "Tamatar (Tomatoes), chopped - 2 medium",
      "Lal mirch powder (Red chili powder) - 1 tsp",
      "Namak (Salt) - 1 tsp or to taste",
      "Haldee powder (Turmeric powder) - ¼ tsp",
      "Hari mirch (Green chilies), chopped - 2-3",
      "Hara dhania (Fresh coriander), chopped - ¼ Cup",
      "Garam masala powder (Whole spice powder) - ¼ tsp",
    ],
    steps: [
      "In a bowl, add eggs, whisk well and set aside.",
      "In a pot, add oil, onion and sauté until translucent.",
      "Add cumin seeds, tomatoes, red chili powder, salt, turmeric powder, green chilies and mix well, cover & cook for 2 minutes.",
      "Add fresh coriander and mix.",
      "Add beaten eggs and mix well for 2-3 minutes.",
      "Sprinkle whole spice powder and serve.",
    ],
  },

  "chana-bhatura": {
    title: "Chana Bhatura",
    ingredients: [
      "Saunf (Fennel seeds) - ½ tsp",
      "Zeera (Cumin seeds) - 1 tsp",
      "Tez paat (Bay leaf) - 1",
      "Javitri (Mace) - 1 piece",
      "Laung (Cloves) - 2",
      "Oil - ½ Cup",
      "Rai dana (Mustard seeds) - ½ tsp",
      "Zeera (Cumin seeds) - ½ tsp",
      "Pyaz (Onion), grinded - 1 Cup",
      "Adrak lehsan paste (Ginger garlic paste) - 1½ tsp",
      "Tamatar (Tomato), pureed - 1 Cup",
      "Kashmiri lal mirch - 1 tsp (optional)",
      "Namak (Salt) - 1 tsp or to taste",
      "Dhania (Coriander seeds), roasted & crushed - 1 tsp",
      "Haldee powder (Turmeric powder) - 1 tsp",
      "Lal mirch powder (Red chili powder) - 1 tsp",
      "Pani (Water) - 2-3 tbs",
      "Chanay (Chickpeas), boiled - 500 gms",
      "Leftover water from boiled chickpeas - 1 Cup",
      "Maida (All-purpose flour) - 2 Cups",
      "Sooji (Semolina) - 1/3 Cup",
      "Cheeni (Sugar), powdered - 1 tsp",
      "Baking powder - 1 tsp",
      "Baking soda - ¼ tsp",
      "Namak (Salt) - ½ tsp or to taste",
      "Dahi (Yogurt) - ¼ Cup",
      "Pani (Water) - ½ Cup or as required",
    ],
    steps: [
      "In a small frying pan, add fennel seeds, cumin seeds, bay leaf, mace, and cloves. Roast until fragrant and let cool.",
      "Grind the roasted spices in a spice mixer to make a coarse powder. Set aside.",
      "In a pot, add oil, mustard seeds, cumin seeds and mix well.",
      "Add onion and cook for 3-4 minutes.",
      "Add ginger garlic paste and mix well.",
      "Add tomato puree and cook for 2 minutes.",
      "Add kashmiri lal mirch and mix. Then add salt, coriander seeds, turmeric powder, ground spice powder, and red chili powder. Mix well.",
      "Add water and cook until oil separates.",
      "Add boiled chickpeas and mix well.",
      "Add leftover chickpea water, mix, cover, and simmer for 6-8 minutes.",
      "In a bowl, add flour, semolina, sugar, baking powder, baking soda, salt and mix.",
      "Add yogurt and mix well.",
      "Gradually add water and knead until dough forms. Cover and rest for 1-2 hours.",
      "Grease hands with oil and knead dough again.",
      "Take a small piece, make a ball, grease surface and rolling pin with oil, and roll it out.",
      "Heat oil in a wok and fry bhatura until golden brown, pouring hot oil while frying.",
    ],
  },
  "egg-cheese-toast": {
    title: "Egg Cheese Toast",
    ingredients: [
      "Bread slices - 2 large",
      "Makhan (Butter), soft - as required",
      "Olper’s Cheddar cheese slice - 1",
      "Mortadella slices - 2",
      "Olper’s Mozzarella cheese - as required",
      "Anda (Egg) - 1",
      "Kali mirch (Black pepper), crushed - to taste",
      "Himalayan pink salt - to taste",
      "Hara dhania (Fresh coriander), chopped",
    ],
    steps: [
      "On a baking tray lined with butter paper, place two large bread slices and apply butter on one bread slice.",
      "Add cheddar cheese, mortadella slices, and mozzarella cheese over the buttered slice.",
      "With the help of a bowl, press down in the center of the other slice to create a well, then place it on top of the cheese layer.",
      "Apply butter on the top slice, crack an egg into the well, and sprinkle crushed black pepper and pink salt over the egg.",
      "Add mozzarella cheese around the sides of the egg and poke the egg yolk gently with a wooden skewer.",
      "Bake in a preheated oven at 190°C for 10–12 minutes using both upper and lower grills.",
      "Sprinkle with fresh coriander and serve with tea.",
    ],
  },
  katlama: {
    title: "Katlama",
    ingredients: [
      "Maida (All-purpose flour) - 1 Cup",
      "Atta (Wheat flour) - 1 Cup",
      "Namak (Salt) - ½ tsp",
      "Oil - 2 tbs",
      "Pani (Water) - ½ Cup or as required",
      "Anda (Egg) - 1",
      "Baisan (Gram flour) - 1 Cup",
      "Lal mirch powder (Red chili powder) - 1 tbs",
      "Zeera (Cumin seeds), roasted & crushed - 1 tbs",
      "Dhania (Coriander seeds), crushed - 1 tbs",
      "Namak (Salt) - ½ tsp or to taste",
      "Zarda ka rang (Yellow food color) - ½ tsp",
      "Pani (Water) - ½ Cup or as required",
      "Anardana (Dried pomegranate seeds) - 1 tbs",
      "Hari moong daal (Green gram), soaked - ½ Cup",
      "Oil - for frying",
    ],
    steps: [
      "In a bowl, add all-purpose flour, wheat flour, salt and oil.",
      "Gradually add water and knead well to form a dough. Cover and let it rest for 30 minutes.",
      "In another bowl, whisk egg, then add gram flour, red chili powder, cumin seeds, coriander seeds, salt, yellow food color, and water. Mix well to make a thick paste.",
      "Grease your hands with oil and knead the dough again.",
      "Take a small portion of dough, make a ball, sprinkle flour and roll it out using a rolling pin.",
      "Spread the prepared gram flour paste on it.",
      "Sprinkle dried pomegranate seeds and soaked green gram on top.",
      "Heat oil in a wok and fry the katlama until golden brown.",
    ],
  },
  "anday-chanay": {
    title: "Anday Chanay",
    ingredients: [
      "Mutton haddi guddi (Soup bones) - 300 gms",
      "Badi elaichi (Black cardamom) - 2",
      "Hari elaichi (Green cardamom) - 2",
      "Laung (Cloves) - 3",
      "Sabut kali mirch (Black peppercorns) - 3-4",
      "Darchini (Cinnamon sticks) - 2",
      "Namak (Salt) - 1 tsp or to taste",
      "Adrak lehsan paste (Ginger garlic paste) - 1 tsp",
      "Pani (Water) - 1 litre or as required",
      "Chanay (Chickpeas), soaked overnight with ½ tbs baking soda - 1½ Cup",
      "Namak (Salt) - 1 tsp or to taste",
      "Kali mirch powder (Black pepper powder) - 1 tsp",
      "Pani (Water) - 6 Cups or as required",
      "Ghee - ¼ Cup",
      "Pyaz (Onion), grinded - 2 medium",
      "Tamatar (Tomato), pureed - 1 medium",
      "Adrak lehsan paste (Ginger garlic paste) - 1½ tsp",
      "Lal mirch powder (Red chili powder) - ½ tbs or to taste",
      "Haldee powder (Turmeric powder) - 1 tsp",
      "Dhania (Coriander seeds), crushed - 1½ tsp",
      "Namak (Salt) - 1 tsp or to taste",
      "Jaifil powder (Nutmeg powder) - ¼ tsp",
      "Javatri powder (Mace powder) - ¼ tsp",
      "Zeera powder (Cumin powder) - 1 tsp",
      "Tatri (Citric acid) - 1 pinch (optional)",
      "Saunf (Fennel seeds), powdered - 1½ tsp",
      "Aloo (Potato), boiled & mashed - 1 large",
      "Kashmiri lal mirch (Kashmiri red chilli powder) - ½ tsp",
      "Kali mirch powder (Black pepper powder) - 1 tsp",
      "Garam masala powder - ½ tsp",
      "Kasuri meethi (Dried fenugreek leaves) - 1 tsp",
      "Baking soda - ¼ tsp",
      "Anday (Eggs), boiled - 5",
      "Hara dhania (Fresh coriander), chopped",
    ],
    steps: [
      "In a pot, add mutton soup bones, black cardamom, green cardamom, cloves, black peppercorns, cinnamon sticks, salt, ginger garlic paste, and water. Mix well and bring it to a boil.",
      "Cover and cook on medium flame for 40–50 minutes. Strain and set the stock aside.",
      "In a separate pot, add chickpeas, salt, black pepper powder, and water. Bring to a boil, then cover and cook on medium flame until tender (approx. 30 minutes).",
      "In another pot, add ghee and let it melt.",
      "Add onion, tomato, and ginger garlic paste. Mix well, cover and cook on low flame until oil separates.",
      "Add red chili powder, turmeric powder, crushed coriander seeds, salt, nutmeg powder, mace powder, cumin powder, citric acid, and fennel seed powder. Mix and cook for 2–3 minutes.",
      "Add mashed potato, mix well, and cook for 5 minutes.",
      "Add cooked chickpeas and mix well.",
      "Add prepared stock, mix, bring to boil, then cover and cook on low flame for 15 minutes.",
      "Add Kashmiri red chili powder, black pepper powder, garam masala powder, fenugreek leaves, and baking soda. Cook for another 2–3 minutes.",
      "Add boiled eggs and fresh coriander, cover and simmer on low flame for 8–10 minutes.",
      "Garnish with fresh coriander and serve.",
    ],
  },
  "mini-qeema-naan": {
    title: "Mini Qeema Naan",
    ingredients: [
      "Cooking oil - 3–4 tbs",
      "Pyaz (Onion), chopped - 2 medium",
      "Beef qeema (Mince) - 350g",
      "Lehsan (Garlic), crushed - 1 tbs",
      "Adrak (Ginger), crushed - ½ tbs",
      "Hari mirch (Green chilli), chopped - 1½ tbs",
      "Himalayan pink salt - 1 tsp or to taste",
      "Sabut dhania (Coriander seeds), crushed - 1 tbs",
      "Zeera powder (Cumin powder) - 1½ tsp",
      "Lal mirch powder (Red chilli powder) - 1½ tsp or to taste",
      "Garam masala powder - 1 tsp",
      "Lal mirch (Red chilli), crushed - ½ tsp",
      "Ajwain (Carom seeds) - ¼ tsp",
      "Water - 2–3 tbs or as required",
      "Olper’s Cream - ½ Cup",
      "Shimla mirch (Capsicum), cubes - ¼ Cup",
      "Hara dhania (Fresh coriander), chopped - handful",
      "Dahi (Yogurt) - 1 Cup",
      "Olper’s Cream - ½ Cup",
      "Hari mirch (Green chilli), crushed - ½ tbs",
      "Zeera (Cumin seeds), roasted & crushed - 1 tsp",
      "Hara dhania (Fresh coriander), crushed - 1 tbs",
      "Lehsan paste (Garlic paste) - 1 tsp",
      "Himalayan pink salt - ¼ tsp or to taste",
      "Podina (Mint leaves), crushed - 1 tbs",
      "Warm water - ½ Cup",
      "Bareek cheeni (Caster sugar) - ½ tbs",
      "Khameer (Instant yeast) - 2½ tsp",
      "Dahi (Yogurt) - ½ Cup",
      "Cooking oil - 2 tbs",
      "Himalayan pink salt - 1½ tsp or to taste",
      "Maida (All-purpose flour), sifted - 2½ Cups",
      "Atta (Wheat flour), sifted - 1 Cup",
      "Water - 3–4 tbs or as required",
      "Cooking oil - 1 tsp",
      "Cheddar cheese, grated - as required",
      "Mozzarella cheese, grated - as required",
      "Anday ki zardi (Egg yolk) - 1",
      "Doodh (Milk) - 1 tbs",
      "Safed til (Sesame seeds)",
      "Makhan (Butter), melted",
      "Hara dhania (Fresh coriander), chopped",
    ],
    steps: [
      "In a frying pan, add oil and onions, sauté until translucent.",
      "Add beef mince, garlic, ginger, green chilli and cook until it changes color.",
      "Add pink salt, coriander seeds, cumin powder, red chilli powder, garam masala, crushed red chilli, and carom seeds. Mix well and cook for 2–3 minutes.",
      "Add water, cover and cook on low flame for 4–5 minutes. Cook on high flame to dry excess moisture.",
      "Turn off the flame. Add cream, capsicum, fresh coriander, mix well.",
      "Turn flame on again and cook for 1–2 minutes. Set aside.",
      "In a bowl, add yogurt, cream, green chilli, cumin seeds, fresh coriander, garlic paste, salt, mint leaves and whisk well. Set aside (this is the chutney).",
      "In a separate bowl, combine warm water, caster sugar, and instant yeast. Mix and let bloom for 5–10 minutes.",
      "Add yogurt, oil, salt and whisk. Then add all-purpose flour and wheat flour.",
      "Gradually add water and knead into a dough. Grease with oil, cover and let rise in a warm place for 1 hour or until doubled.",
      "Knead again, divide into two parts. Take one part (170g), roll it out, and cut two circles (7 inch and 4.5 inch).",
      "Place grated cheddar and mozzarella around the edge of the larger circle. Apply water on edges, fold over cheese and seal.",
      "Prick with a fork, add qeema filling in center, place smaller dough circle over it, seal and prick again.",
      "In a bowl, whisk together egg yolk and milk. Brush it on naan and sprinkle sesame seeds.",
      "Place in air fryer (with baking paper) and bake at 170°C for 7–8 minutes.",
      "After baking, brush with melted butter, sprinkle fresh coriander, cover and rest for 5 minutes. Serve!",
    ],
  },
  "pizza-omelette": {
    title: "Pizza Omelette",
    ingredients: [
      "Makhan (Butter), melted - 3–4 tbs",
      "Lehsan (Garlic), chopped - ½ tbs",
      "Dried oregano - ¼ tsp",
      "Anday (Eggs) - 3–4",
      "Olper’s Milk - 2 tbs",
      "Himalayan pink salt - to taste",
      "Kali mirch (Black pepper), crushed - to taste",
      "Hara dhania (Fresh coriander), chopped - 1 tbs",
      "Makhan (Butter) - 2 tbs",
      "Pyaz (Onion), chopped - 3 tbs",
      "Tamatar (Tomato), chopped - 3 tbs",
      "Hari mirch (Green chilli), chopped - ½ tbs",
      "Bread slices - as required",
      "Pizza sauce - 2 tbs or as required",
      "Olper’s Cheddar cheese - 4 tbs or as required",
      "Olper’s Mozzarella cheese - 4 tbs or as required",
      "Shimla mirch (Capsicum), rings - as required",
      "Tamatar (Tomato), cubes - as required",
      "Pyaz (Onion), cubes - as required",
      "Black olives, slices - as required",
      "Lal mirch (Red chilli), crushed - to taste",
      "Dried oregano - to taste",
    ],
    steps: [
      "In a small bowl, add melted butter, garlic, and dried oregano. Mix well and set aside.",
      "In another bowl, add eggs, milk, pink salt, crushed black pepper, fresh coriander and whisk well.",
      "In an 8-inch frying pan, add 2 tbs butter and let it melt.",
      "Add onion, tomato, and green chilli. Sauté for 1–2 minutes.",
      "Add the whisked eggs and cook on low flame for 2–3 minutes, gently stirring with a rubber spatula.",
      "When the eggs are mostly set on the bottom but still liquid on top, place bread slices over the eggs.",
      "Gently press the bread to set into the eggs and cook on low flame for 1–2 minutes.",
      "Brush the top of the bread slices with the prepared garlic butter.",
      "Carefully flip the omelette using a flat plate.",
      "Spread pizza sauce over the flipped bread side.",
      "Top with cheddar cheese, mozzarella cheese, capsicum rings, tomato cubes, onion cubes, and black olive slices.",
      "Sprinkle with crushed red chilli and dried oregano.",
      "Cover and cook on low flame until cheese melts (2–3 minutes).",
      "Cut into slices and serve hot!",
    ],
  },
  "spicy-cream-eggs": {
    title: "Spicy Cream Eggs",
    ingredients: [
      "Cooking oil - 1/3 Cup",
      "Lehsan (Garlic), sliced - 6–8 cloves",
      "Sukhi lal mirch (Dried red chillies) - 7–8",
      "Mongphali (Peanuts), roasted - 1½ tbs",
      "Til (Sesame seeds), roasted - 2 tsp",
      "Himalayan pink salt - ½ tsp or to taste",
      "Sirka (Vinegar) - 2 tsp",
      "Paprika powder - 1 tsp",
      "Olper’s Cream - ½ Cup",
      "Prepared Mexican chilli oil - ½ tbs or as required",
      "Anday (Eggs) - 4",
      "Himalayan pink salt - to taste",
      "Kali mirch (Black pepper), crushed - to taste",
      "Hara pyaz (Spring onion) leaves, chopped",
    ],
    steps: [
      "In a saucepan, heat the cooking oil.",
      "Add sliced garlic and fry for about 1 minute.",
      "Add dried red chillies, mix and sauté briefly.",
      "Add roasted peanuts, mix well, and fry for another 30 seconds.",
      "Strain the oil using a strainer and let it cool.",
      "In a blender, add fried chillies, garlic, peanuts, sesame seeds, pink salt, vinegar, strained oil, and paprika powder.",
      "Blend into a thick paste — this is the Mexican chilli oil. (Store in a jar at room temperature for up to 1 month.)",
      "In an 8-inch frying pan, add cream and ½ tbs of the prepared Mexican chilli oil. Stir gently and cook on low flame for 1 minute.",
      "Crack in the eggs one by one. Cover and cook on low flame for 2–3 minutes until eggs are just set.",
      "Sprinkle with pink salt and crushed black pepper.",
      "Drizzle more Mexican chilli oil on top and garnish with chopped spring onion leaves.",
      "Serve hot with bread!",
    ],
  },
  "qeema-paratha": {
    title: "Qeema Paratha",
    ingredients: [
      "Qeema (Mince) - 250 gms",
      "Dahi (Yogurt) - 4 tbs",
      "Tandoori masala - 1 tbs",
      "Haldee powder (Turmeric powder) - ¼ tsp",
      "Lal mirch powder (Red chili powder) - 1 tsp or to taste",
      "Namak (Salt) - ¼ tsp or to taste",
      "Adrak lehsan paste (Ginger garlic paste) - 1 tsp",
      "Lemon juice - 1 tsp",
      "Oil - 2–3 tbs",
      "Hara dhania (Fresh coriander) - ½ Cup",
      "Hari mirch (Green chilies), chopped - 3–4",
      "Atta (Flour) - 2 Cups",
      "Namak (Salt) - ¼ tsp or to taste",
      "Cheeni (Sugar) - ½ tbs",
      "Anda (Egg) - 1",
      "Oil/Ghee - 3–4 tbs",
      "Pani (Water) - as required",
      "Ghee - for frying",
    ],
    steps: [
      "In a bowl, combine mince, yogurt, tandoori masala, turmeric powder, red chili powder, salt, ginger garlic paste, and lemon juice. Mix well and marinate for 30 minutes.",
      "In a frying pan, heat oil and add marinated mince. Cook until it changes color.",
      "Cover and cook on low flame for 6–8 minutes. Then cook on high flame until all moisture evaporates. Let it cool down.",
      "In a chopper, blend cooked mince with fresh coriander and chopped green chilies until well combined.",
      "In a bowl, add flour, salt, sugar, egg, and oil. Mix well.",
      "Gradually add water and knead into a dough. Cover and let it rest for 20 minutes.",
      "Take a small portion of dough, make a ball, coat with dry flour, and roll it out using a rolling pin.",
      "Place mince filling in the center, fold all sides over it, press down and prick with a stick, then press again.",
      "Coat again in dry flour and roll out carefully.",
      "Heat a griddle and fry the paratha on both sides using ghee until golden brown.",
      "Serve hot with chutney or raita!",
    ],
  },
  "cream-pancakes": {
    title: "Cream Pancakes",
    ingredients: [
      "Anday (Eggs) - 3",
      "Olper’s milk - 1 Cup",
      "Bareek cheeni (Caster sugar) - 3 tbs",
      "Baking powder - 1 tbs",
      "Himalayan pink salt - ½ tsp",
      "Vanilla essence - 1 tsp",
      "Makhan (Butter), melted unsalted - 1 Cup",
      "Olper's cream (room temperature) - 1 Cup",
      "Maida (All-purpose flour), sifted - 2 Cups",
      "Olper's cream (chilled) - as required",
      "Makhan (Butter), cubes - as required",
      "Maple syrup - as required",
    ],
    steps: [
      "In a bowl, add eggs and whisk well.",
      "Add milk, caster sugar, baking powder, pink salt, vanilla essence, melted butter, and room-temperature cream. Whisk until smooth.",
      "Gradually add sifted all-purpose flour while continuously whisking until a smooth batter forms.",
      "Transfer the batter to a squeeze bottle for easy pouring.",
      "Heat a non-stick frying pan and lightly grease it with cooking oil.",
      "Squeeze batter onto the pan and cook on low flame for 1–2 minutes on each side or until golden brown. Repeat for all pancakes (makes 5).",
      "Layer pancakes with chilled cream in between.",
      "Top with butter cubes, drizzle maple syrup, and serve warm!",
    ],
  },
};
// ==========================Breakfast recipies==========================
// ==========================Lunch/Dinner recipies==========================
const lunchdinnerrecipes = {
  "chilli-fried-rice": {
    title: "Chilli Fried Rice",
    ingredients: [
      "Boneless chicken julienne 400g",
      "Himalayan pink salt ½ tsp or to taste",
      "Cornflour 2 tbs",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Kali mirch powder (Black pepper powder) 1 tsp",
      "Soy sauce 2 tbs",
      "Adrak lehsan paste (Ginger garlic paste) 1 tsp",
      "Anda (Egg) 1",
      "Cooking oil ½ Cup",
      "Lehsan (Garlic) chopped 1 tbs",
      "Adrak (Ginger) julienne 1-inch piece",
      "Hari mirch (Green chillies) 3-4",
      "Pyaz (Onion) sliced 1 medium",
      "Shimla mirch (Capsicum) julienne 1 medium",
      "Himalayan pink salt ½ tsp or to taste",
      "Lal mirch powder (Red chilli powder) ½ tsp or to taste",
      "Sugar powdered ¼ tsp",
      "Soy sauce 2 tbs",
      "Chilli sauce 2 tbs",
      "Dark soy sauce 1 tsp",
      "Chicken yakhni (Stock) ¼ Cup",
      "Cornflour 1 tbs",
      "Cooking oil 2 tbs",
      "Anday (Eggs) whisked 2",
      "Lehsan (Garlic) chopped 1 tbs",
      "Gajar (Carrot) julienne ½ Cup",
      "Shimla mirch (Capsicum) julienne ½ Cup",
      "Band gobhi (Cabbage) 1 Cup",
      "Chawal (Rice) boiled 2 Cups",
      "Kali mirch powder (Black pepper powder) 1 tsp",
      "Himalayan pink salt ½ tsp or to taste",
      "Safed mirch powder (White pepper powder) ½ tsp",
      "Chicken powder ½ tbs",
      "Soy sauce 2 tbs",
      "Chilli sauce ½ tbs",
      "Sirka (Vinegar) ½ tbs",
      "Hara pyaz (Spring onion) leaves handful",
      "Hara pyaz (Spring onion) leaves",
    ],
    steps: [
      "In a bowl, add chicken, pink salt, cornflour, red chilli powder, black pepper powder, soy sauce, ginger garlic paste, egg, mix well, cover & marinate for 15 minutes.",
      "In frying pan, add cooking oil, marinated chicken & fry on medium flame until golden & crispy.",
      "In same frying pan, add garlic, ginger, green chillies & mix well.",
      "Add onion, capsicum, mix well & cook on high flame for a minute.",
      "Add pink salt, red chilli powder, sugar, soy sauce, chilli sauce, dark soy sauce & mix well.",
      "Add fried chicken & mix well.",
      "In cornflour, add chicken stock & mix well.",
      "Now add dissolved cornflour, mix well & cook on high flame for a minute & set aside.",
      "In a wok, add cooking oil, eggs & cook until it crumbled.",
      "Add garlic & fry until light golden.",
      "Add carrot, capsicum, cabbage, mix well & cook on high flame for 1 minute.",
      "Add boiled rice, black pepper powder, pink salt, white pepper powder, chicken powder, soy sauce, chilli sauce, vinegar, mix well & cook for a minute.",
      "Add spring onion leaves & mix well.",
      "Garnish with green onion leaves & serve!",
    ],
  },
  "kabab-platter": {
    title: "Kabab Platter",
    ingredients: [
      "Boneless chicken cubes 500g",
      "Himalayan pink salt 1 tsp or to taste",
      "Kacha papita (Raw papaya) paste 1 tsp",
      "Dahi (Yogurt) whisked ¾ Cup",
      "Adrak lehsan paste (Ginger garlic paste) ½ tbs",
      "Kashmiri lal mirch (Kashmiri red chilli) powder 1 tsp",
      "Sabut dhania (Coriander seeds) crushed 1 tsp",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Zeera (Cumin seeds) roasted & crushed ½ tsp",
      "Haldi powder (Turmeric powder) ½ tsp",
      "Tatari (Citric acid) ½ tsp",
      "Chaat masala 1 tsp",
      "Kali mirch powder (Black pepper powder) ¼ tsp",
      "Garam masala powder ½ tsp",
      "Red food color 2-3 drops (optional)",
      "Cooking oil 2-3 tbs",
      "Koyal (Charcoal) for smoke",
      "Lehsan (Garlic) cloves 5-6",
      "Hari mirch (Green chillies) 6-7",
      "Adrak (Ginger) 1-inch piece",
      "Zeera (Cumin seeds) 1 tsp",
      "Podina (Mint leaves) handful",
      "Hara dhania (Fresh coriander) handful",
      "Water ¼ Cup",
      "Dahi (Yogurt) whisked ½ Cup",
      "Cream 3 tbs (optional)",
      "Dhania powder (Coriander powder) 1 tsp",
      "Garam masala powder ½ tsp",
      "Lemon juice 2 tbs",
      "Green food color 2-3 drops (optional)",
      "Kaju (Cashew nuts) 8-10",
      "Hari mirch (Green chillies) 4-5",
      "Lehsan (Garlic) 5-6",
      "Hara dhania (Fresh coriander) 1-2 tbs",
      "Dahi (Yogurt) whisked ½ Cup",
      "Cream 4-5 tbs",
      "Kali mirch powder (Black pepper powder) ½ tsp",
      "Safed mirch powder (White pepper powder) ½ tsp",
      "Kasuri methi (Dried fenugreek leaves) 1 tsp",
      "Lemon juice 1 tbs",
      "Lemon wedges",
      "Hara dhania (Fresh coriander) chopped",
      "Cream",
    ],
    steps: [
      "In a bowl, add chicken, pink salt, raw papaya paste & mix well, cover & marinate for 30 minutes.",
      "In a bowl, add yogurt, ginger garlic paste, Kashmiri red chilli powder, coriander seeds, red chilli powder, cumin seeds, turmeric powder, citric acid, chaat masala, black pepper powder, garam masala powder, red food color & mix well.",
      "Add marinated chicken & mix well, cover & marinate for 2 hours in refrigerator.",
      "On a griddle, add cooking oil & heat it.",
      "Add marinated chicken & cook on medium flame for 3-4 minutes, cover & cook on low flame for 4-5 minutes then cook on high flame until chicken is done (3-4 minutes).",
      "Give coal smoke for 2 minutes.",
      "In a bowl, add chicken, pink salt, raw papaya paste & mix well, cover & marinate for 30 minutes.",
      "In a blending jug, add garlic, green chillies, ginger, cumin seeds, mint leaves, fresh coriander & blend well to make a paste.",
      "Transfer it to a bowl, add yogurt, cream, coriander powder, garam masala powder, lemon juice, green food color & whisk well.",
      "Add marinated chicken & mix well, cover & marinate for 2 hours in refrigerator.",
      "On a griddle add cooking oil & heat it.",
      "Add marinated chicken & cook on medium flame for 3-4 minutes, cover & cook on low flame for 4-5 minutes then cook on high flame until chicken is done (3-4 minutes).",
      "Give coal smoke for 2 minutes.",
      "Garnish with lemon wedges, cream, fresh coriander, onion rings, lettuce leaves & serve with naan!",
      "In a bowl, add chicken, pink salt, raw papaya paste & mix well, cover & marinate for 30 minutes.",
      "In a spice grinder, add cashew nuts, green chillies, ginger, garlic, fresh coriander, water & grind well to make a thick paste.",
      "Transfer it to a bowl, add yogurt, cream, black pepper powder, white pepper powder, garam masala powder, dried fenugreek leaves, lemon juice & whisk well.",
      "Add marinated chicken & mix well, cover & marinate for 2 hours in refrigerator.",
      "On a griddle, add cooking oil & heat it.",
      "Add marinated chicken & cook on medium flame for 3-4 minutes, cover & cook on low flame for 4-5 minutes then cook on high flame until chicken is done (3-4 minutes).",
      "Give coal smoke for 2 minutes.",
    ],
  },
  "khatri-biryani": {
    title: "Khatri Biryani",
    ingredients: [
      "Ghee (Clarified butter) 3 tbs",
      "Tamatar (Tomatoes) 4 medium",
      "Zeera (Cumin seeds) ½ tsp",
      "Hari mirch (Green chilli) paste 1 tsp",
      "Sabut dhania (Coriander seeds) crushed 1 tsp",
      "Haldi powder (Turmeric powder) ½ tsp",
      "Lal mirch (Red chilli) crushed ½ tsp",
      "Himalayan pink salt ½ tsp or to taste",
      "Podina (Mint leaves) chopped 2 tbs",
      "Hara dhania (Fresh coriander) chopped 3 tbs",
      "Kari patta (Curry leaves) 14-15",
      "Ghee (Clarified butter) ½ Cup",
      "Adrak (Ginger) crushed 1 tbs",
      "Lehsan (Garlic) crushed 1 tbs",
      "Chicken mix boti 750g",
      "Dahi (Yogurt) ¾ Cup",
      "Lal mirch (Red chilli) crushed 1 tbs",
      "Sabut dhania (Coriander seeds) crushed 1 tbs",
      "Jaifil powder (Nutmeg powder) ¼ tsp",
      "Javitri powder (Mace powder) ¼ tsp",
      "Haldi powder (Turmeric powder) 1 tsp",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Himalayan pink salt 1 tsp or to taste",
      "Darchini (Cinnamon stick) 2-3",
      "Hari elaichi (Green cardamom) 3-4",
      "Badi elaichi (Black cardamom) 2",
      "Sabut kali mirch (Black peppercorns) 1 tsp",
      "Zeera (Cumin seeds) 1 tsp",
      "Badiyan ka phool (Star anise) 2",
      "Laung (Cloves) 3-4",
      "Hari mirch (Green chilli) paste 1 & ½ tbs",
      "Podina (Mint leaves) chopped handful",
      "Hara dhania (Fresh coriander) chopped handful",
      "Tamatar (Tomatoes) sliced 2 medium",
      "Water 2 & ½ Cups",
      "Pyaz (Onion) fried 4 tbs",
      "Aloo bukhara (Dried plums) 6-7",
      "Sukhi imli (Dried tamarind) ¼ Cup",
      "Podina (Mint leaves) chopped handful",
      "Hara dhania (Fresh coriander) chopped handful",
      "Kari patta (Curry leaves) 10-12",
      "Zarda ka rang (Orange food color) ½ tsp",
      "Water 1-2 tbs",
      "Chawal (Rice) Sella 750g (50% boiled with salt & whole spices)",
      "Ghee (Clarified butter) melted 2 tbs",
    ],
    steps: [
      "In a frying pan, add clarified butter & let it melt.",
      "Add tomatoes, cumin seeds, green chilli paste, coriander seeds, turmeric powder, red chilli crushed, pink salt, mix well & cook on medium flame until tomatoes are soft (4-5 minutes).",
      "Add mint leaves, fresh coriander, curry leaves, mix well & cook for 1-2 minutes & reserve for later use.",
      "In a pot, add clarified butter & let it melt.",
      "Add ginger, garlic & mix well.",
      "Add chicken & mix well until it changes color.",
      "Add yogurt, red chilli crushed, coriander seeds, nutmeg powder, mace powder, turmeric powder, red chilli powder, pink salt, cinnamon sticks, green cardamom, black cardamom, black peppercorns, cumin seeds, star anise, cloves, green chilli paste, mint leaves, fresh coriander, tomatoes & mix well.",
      "Add water, mix well & bring it to boil, cover & cook on medium flame for 10-12 minutes or until 1 Cup of gravy is left.",
      "In a pot, add prepared tomato chutney, fried onion, dried plum, dried tamarind, mint leaves, fresh coriander & curry leaves.",
      "In water, add orange food color & mix well, add in pot & spread evenly.",
      "Place pot on heat diffuser for steam cooking.",
      "Add boiled rice & pour melted clarified butter, cover with kitchen cloth & lid and steam cook on low flame for 12-15 minutes.",
      "Mix well & serve with yogurt raita & salad!",
    ],
  },
  "mix-veg-pakora": {
    title: "Mix Veg Pakora",
    ingredients: [
      "Baisan (Gram flour) 1 Cup",
      "Chawal ka atta (Rice flour) 2 tbs",
      "Zeera (Cumin seeds) roasted & crushed ½ tsp",
      "Himalayan pink salt ½ tsp or to taste",
      "Lal mirch powder (Red chilli powder) ½ tsp or to taste",
      "Sabut dhania (Coriander seeds) crushed 1 tbs",
      "Baking soda ¼ tsp",
      "Zarda ka rang (Orange food color) ¼ tsp",
      "Ajwain (Carom seeds) ¼ tsp",
      "Hara dhania (Fresh coriander) chopped 1-2 tbs",
      "Water ½ Cup or as required",
      "Aloo (Potatoes) julienne 2 medium",
      "Band gobhi (Cabbage) shredded 1 & ½ Cup",
      "Gajar (Carrot) julienne 1 Cup",
      "Palak (Spinach) chopped 1 Cup",
      "Hara pyaz (Spring onion) chopped ½ Cup",
      "Himalayan pink salt 1 tsp or to taste",
      "Chaat masala 1 & ½ tsp",
      "Kasuri methi (Dried fenugreek leaves) 1 tsp",
      "Cooking oil 1 tsp",
      "Cooking oil for frying",
      "Bhunay chanay (Roasted grams) slit ½ Cup or as required",
      "Chaat masala",
    ],
    steps: [
      "In a bowl, add gram flour, rice flour, cumin seeds, pink salt, red chilli powder, coriander seeds, baking soda, orange food color, carom seeds, fresh coriander, gradually add water & mix until well combined, cover & let it rest for 15-20 minutes.",
      "In a bowl, add potatoes, cabbage, carrot, spinach, spring onion, pink salt, chaat masala, dried fenugreek leaves, cooking oil & mix well.",
      "Add prepared pakora batter & mix well.",
      "In a wok, heat cooking oil & take small quantity of mixture on hand, add roasted grams & fry on low flame until golden & crispy.",
      "Sprinkle chaat masala & serve!",
    ],
  },
  "afghani-pulao": {
    title: "Afghani Pulao",
    ingredients: [
      "Ghee (Clarified butter) ½ Cup",
      "Gajar (Carrots) julienne 1 Cup",
      "Brown sugar ½ tbs",
      "Kishmish (Raisins) ¼ Cup",
      "Pyaz (Onion) chopped 1 medium",
      "Hari elaichi (Green cardamom) 4-5",
      "Zeera (Cumin seeds) 1 tsp",
      "Darchini (Cinnamon sticks) 2",
      "Badi elaichi (Black cardamom) 2",
      "Mutton mix boti (large pieces) 750g",
      "Adrak lehsan paste (Ginger garlic paste) 1 tbs",
      "Kali mirch (Black pepper) crushed ½ tsp",
      "Himalayan pink salt ½ tbs or to taste",
      "Water 5-6 Cups",
      "Chicken cube 1 (optional)",
      "Chawal (Rice) sella 500g (soaked for 2 hours)",
      "Badam (Almonds) fried",
    ],
    steps: [
      "In a cooking pot, add clarified butter & let it melt.",
      "Add carrots, brown sugar, mix well & let them caramelize for 1-2 minutes.",
      "Add raisins & mix well, sauté for a minute & set aside.",
      "In the same pot, add onion, mix well & sauté until translucent.",
      "Add green cardamom, cumin seeds, cinnamon stick, black cardamom, mix well & cook for 1-2 minutes.",
      "Add mutton & mix well until it changes color.",
      "Add ginger garlic paste, black pepper crushed, pink salt, mix well & cook on medium flame for 4-5 minutes.",
      "Add water, chicken cube, mix well & bring it to boil, cover & cook on low flame until meat is tender (40-50 minutes) then take out mutton pieces & set aside.",
      "Add rice, mix well & cook on medium flame until water is reduced (2-3 minutes), cover & cook on low flame for 4-5 minutes or until 80% done.",
      "Add carrots & raisins (reserve half for garnishing), cooked mutton pieces, cover & steam cook on low flame for 10-12 minutes.",
      "Garnish with reserved carrots & raisins, fried almonds & serve with salad & raita!",
    ],
  },
  "white-karahi": {
    title: "White Karahi",
    ingredients: [
      "Saunf (Fennel Seeds) roasted 1 & ½ tsp",
      "Sabut Dhania (Coriander Seeds) roasted 2 tsp",
      "Zeera (Cumin Seeds) 1 & ½ tsp",
      "Kali Mirch (Black Peppercorns) 1 tsp",
      "Elaichi ke danay (Cardamom seeds) whole ¼ tsp",
      "Methi (Fenugreek Leaves) Dried 2 tsp",
      "Garam Masala Powder ½ tsp",
      "Cooking Oil ¼ Cup",
      "Kaju (Cashew nuts) halved 6-8",
      "Chicken karahi cut 800g",
      "Lehsan (Garlic) crushed 1 tbs",
      "Hari mirch (Green chilli) chopped 1 tsp",
      "Himalayan Pink Salt 1 tsp or to taste",
      "Doodh (Milk) 1 Cup",
      "Dahi (Yogurt) whisked ½ Cup",
      "Cheddar Cheese Slices 2-3",
      "Olper’s Cream ½ Cup",
      "Hari Mirch (Green Chillies) 3-4",
      "Adrak (Ginger) julienne (As required)",
      "Lal Mirch (Red Chilli) Crushed ½ tsp",
      "Hara Dhania (Fresh Coriander) chopped Handful",
    ],
    steps: [
      "In mortar & pestle, add fennel seeds, coriander seeds, cumin seeds, black peppercorn, green cardamom seeds, pound coarsely.",
      "Now add dried fenugreek leaves and garam masala powder, pound again then set aside.",
      "In a wok, add cooking oil and heat it.",
      "Add cashews, fry them on low flame until golden then strain them and set aside.",
      "In the same oil, add chicken and fry it on a medium flame for 2-3 minutes or until it changes color.",
      "Add garlic, green chilli and pink salt. Mix well and cook for 2-3 minutes on medium flame.",
      "Now add milk, yogurt, cheese slices, and crushed spices (reserve 1 tbs for later use). Mix well and cook on low flame until oil separates.",
      "Then cover and cook on low flame for 8-10 minutes or until chicken tenders.",
      "Remove the lid, mix again. Add cream, mix it. Add green chillies, ginger, reserved crushed spices, red chilli crushed and fresh coriander. Mix well and cook on low flame for 2 minutes.",
      "In a serving dish pour Creamy Karahi. Garnish with roasted zeera, fried cashews, fresh coriander, and ginger then serve with naan and raita.",
    ],
  },
  "resha-bun-kabab": {
    title: "Resha Bun Kabab",
    ingredients: [
      "Imli pulp (Tamarind pulp) ½ Cup",
      "Lehsan (Garlic) cloves 2-3",
      "Sabut lal mirch (Button red chillies) 3-4",
      "Hari mirch (Green chillies) 2-3",
      "Zeera (Cumin seeds) roasted & crushed 1 tsp",
      "Himalayan pink salt ½ tsp or to taste",
      "Chilli garlic sauce 2 tbs",
      "Hara dhania (Fresh coriander) handful",
      "Podina (Mint leaves) handful",
      "Lehsan (Garlic) cloves 5-6",
      "Hari mirch (Green chillies) 3-4",
      "Zeera (Cumin seeds) 1 tsp",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Himalayan pink salt ½ tsp or to taste",
      "Tatry (Citric acid) ¼ tsp",
      "Lemon juice 2 & ½ tbs",
      "Dahi (Yogurt) 1 Cup",
      "Band gobhi (Cabbage) finely shredded",
      "Mayonnaise 4-5 tbs",
      "Kali mirch (Black pepper) crushed ¼ tsp or to taste",
      "Himalayan pink salt ¼ tsp or to taste",
      "Water 1 & ½ Cup",
      "Soy sauce 1 tbs",
      "Adrak lehsan paste (Ginger garlic paste) 1 tbs",
      "Himalayan pink salt ½ tsp or to taste",
      "Chicken fillets 300g",
      "Anday (Eggs) 3",
      "Himalayan pink salt ¼ tsp or to taste",
      "Kali mirch (Black pepper) crushed ½ tsp or to taste",
      "Ghee (Clarified butter) 2-3 tbs",
      "Burger buns as required",
      "Band gobhi (Cabbage) shredded 1 Cup",
      "Pyaz (Onion) rings",
      "Ghee (Clarified butter) 1 tsp",
    ],
    steps: [
      "In a jug, add tamarind pulp, garlic, button red chillies, green chillies, cumin seeds, pink salt & blend well.",
      "Add chilli garlic sauce, mix well & set aside.",
      "In a grinder, add fresh coriander, mint leaves, garlic, green chillies, cumin seeds, red chilli powder, pink salt, citric acid, lemon juice & blend well.",
      "In yogurt, add blended paste, whisk well & set aside.",
      "In a bowl, add cabbage, mayonnaise, black pepper crushed, pink salt, mix well & set aside.",
      "In a saucepan, add water & bring it to boil.",
      "Add soy sauce, ginger garlic paste, pink salt, chicken & bring it to boil, cover & cook on medium flame until chicken is tender (10-12 minutes).",
      "Let it cool then shred it with the help of fork & set aside.",
      "In a bowl, add eggs, pink salt, black pepper crushed & whisk well.",
      "Add shredded chicken & mix well.",
      "On a heated griddle, add clarified butter, egg & chicken mixture & cook on medium flame from both sides until golden.",
      "Cut the burger buns from middle & toast them from both sides.",
      "On burger bun, add & spread special bun kabab instant chutney, add cabbage, onion rings, prepared resha chicken patty & prepared coleslaw.",
      "Add & spread prepared special bun kabab hari chutney on top burger bun & flip it to make a bun kabab.",
      "Toast bun kabab with clarified butter, cut in half & serve (makes 4-5).",
    ],
  },
  "chicken-chowmein": {
    title: "Chicken Chowmein",
    ingredients: [
      "Water as required",
      "Spaghetti 300g",
      "Namak (Salt) 1 & ½ tsp or to taste",
      "Cooking oil 1-2 tbs",
      "Soy sauce 1 tbs",
      "Sirka (Vinegar) ½ tbs",
      "Safed mirch powder (White pepper powder) 1 tsp",
      "Namak (Salt) ½ tsp or to taste",
      "Lehsan powder (Garlic powder) 1 tsp",
      "Chicken boneless stripes 300g",
      "Baking soda ¼ tsp",
      "Cooking oil 2 tbs",
      "Soy sauce 2 tbs",
      "Chilli sauce 3 tbs",
      "Chilli garlic sauce 1 tbs",
      "Oyster sauce 2 tbs",
      "Til ka tel (Sesame oil) 1 tbs",
      "Cheeni (Sugar) 1 tbs",
      "Namak (Salt) 1 tsp or to taste",
      "Kali mirch powder (Black pepper powder) 1 tsp",
      "Cooking oil 1-2 tbs",
      "Gajar (Carrots) julienne 1 cup",
      "Shimla mirch (Capsicum) julienne 1 cup",
      "Band gobhi (Cabbage) shredded 1 & ½ cups",
      "Cooking oil 2-3 tbs",
      "Lehsan (Garlic) sliced 8-10 cloves",
      "Hara pyaz (Spring onion) white 2 tbs",
      "Spaghetti boiled",
      "Fried Chicken",
      "Prepared chowmein sauce",
      "Stir fried vegetables",
      "Hara pyaz (Spring onion) leaves 1-2 tbs",
    ],
    steps: [
      "In boiling water add spaghettis & mix well.",
      "Add salt, mix well & boil until tender (4-5 minutes).",
      "On a pot place a strainer, strain it & rinse with tap water. Add oil, mix well, strain & set aside.",
      "In a bowl add soy sauce, vinegar, white pepper powder, salt, garlic powder & mix well.",
      "Add chicken boneless stripes & mix well.",
      "Add baking soda & mix well. Cover & let it rest for 15 minutes.",
      "In a wok add cooking oil, marinated chicken, cook for 4-5 minutes on medium flame or until done & set aside.",
      "In a bowl add soy sauce, chilli sauce, chilli garlic sauce, oyster sauce, sesame oil, sugar, salt, black pepper powder, mix well. Chowmein sauce is ready & set aside.",
      "In the same wok add cooking oil, carrots, capsicum, cabbage, mix well & sauté for 2 minutes. Take out & set aside.",
      "In same wok add cooking oil, garlic & mix well.",
      "Add spring onion white, mix well & sauté for a minute.",
      "Add boiled spaghettis & mix well for a minute.",
      "Add cooked chicken & mix well.",
      "Add prepared chowmein sauce, mix well & cook for 1 minute on high flame.",
      "Add stir fried vegetables & mix well.",
      "Add spring onion leaves, mix well & serve.",
    ],
  },
  "lauki-ki-sabzi": {
    title: "Lauki Ki Sabzi",
    ingredients: [
      "Lauki (Bottle gourd) 500g",
      "Kashmiri lal mirch (Kashmiri red chilli) powder ½ tbs",
      "Himalayan pink salt 1 tsp or to taste",
      "Haldi powder (Turmeric powder) ½ tsp",
      "Dhania powder (Coriander powder) 1 tsp",
      "Baisan (Gram flour) 2 tbs",
      "Cooking oil for frying",
      "Cooking oil ¼ Cup",
      "Pyaz (Onion) chopped 2 medium",
      "Zeera (Cumin seeds) 1 tsp",
      "Hari mirch (Green chillies) sliced 2-3",
      "Adrak lehsan (Ginger garlic) crushed 1 tbs",
      "Tamatar (Tomatoes) pureed 1 Cup",
      "Dhania powder (Coriander powder) ½ tbs",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Haldi powder (Turmeric powder) ¼ tsp",
      "Himalayan pink salt 1 tsp or to taste",
      "Kashmiri lal mirch (Kashmiri red chilli) powder 1 tsp",
      "Garam masala powder ½ tsp",
      "Dahi (Yogurt) whisked ½ Cup",
      "Water 1 Cup or as required",
      "Pyaz (Onion) thick slices 1 medium",
      "Hara dhania (Fresh coriander) chopped 1 tbs",
      "Kasuri methi (Dried fenugreek leaves) ½ tbs",
      "Hara dhania (Fresh coriander) chopped",
    ],
    steps: [
      "Peel bottle gourd & cut into thick slices.",
      "In a bowl, add bottle gourd, kashmiri red chilli powder, pink salt, turmeric powder, coriander powder & mix well, cover & let them rest for 15 minutes.",
      "Add gram flour & mix well.",
      "In frying pan, add cooking oil & shallow fry on medium flame from both sides until golden.",
      "In a wok, add cooking oil, onion & sauté until translucent.",
      "Add cumin seeds, mix well & fry until light golden.",
      "Add green chillies, ginger garlic & mix well.",
      "Add pureed tomatoes, coriander powder, red chilli powder, turmeric powder, pink salt, kashmiri red chilli powder, garam masala powder, mix well & cook on medium flame for 2-3 minutes.",
      "Add yogurt & mix well, cover & cook on low flame until oil separates (8-10 minutes).",
      "Add water & mix well.",
      "Add cooked lauki, onion, mix well & bring it to boil.",
      "Add fresh coriander, dried fenugreek leaves & mix well, cover & cook on low flame for 15-20 minutes.",
      "Garnish with fresh coriander & serve!",
    ],
  },
  "crispy-burger": {
    title: "Crispy Burger",
    ingredients: [
      "Mayonnaise ¾ Cup",
      "Mustard paste 1 & ½ tbs",
      "Paprika powder ½ tsp",
      "Namak (Salt) 1 pinch or to taste",
      "Lal mirch powder (Red chilli powder) 1 tsp or to taste",
      "Pickled water 3 tbs",
      "Mozzarella cheese grated 250g",
      "Lehsan powder (Garlic powder) 1 tsp",
      "Maida (All-purpose flour) 1 Cup or as required",
      "Anday (Eggs) whisked 2",
      "Breadcrumbs 1 Cup or as required",
      "Cooking oil for frying",
      "Paprika powder ½ tbs",
      "Namak (Salt) 1 tsp or to taste",
      "Onion powder ½ tbs",
      "Lal mirch powder (Red chilli powder) ½ tbs or to taste",
      "Lehsan powder (Garlic powder) ½ tbs",
      "Boneless chicken preferably thighs 3 pieces",
      "Maida (All-purpose flour) 1 Cup or as required",
      "Water 1 Cup or as required",
      "Cooking oil for frying",
      "Burger buns",
      "Mayonnaise",
      "Iceberg shredded",
      "Pickled jalapenos sliced",
    ],
    steps: [
      "In a bowl, add mayonnaise, mustard paste, paprika powder, salt, red chilli powder, pickled water, whisk well & set aside.",
      "In a bowl, add mozzarella cheese, garlic powder & mix well.",
      "Take a small quantity of mixture (70g) & make patty of equal sizes.",
      "Coat with all-purpose flour, dip in whisked eggs then coat with breadcrumbs then again dip in whisked eggs & coat with breadcrumbs & freeze for 15-20 minutes.",
      "In a wok, heat cooking oil & fry on medium flame until golden & crispy (2 minutes).",
      "In a bowl, add paprika powder, salt, onion powder, red chilli powder, garlic powder & mix well.",
      "Pound chicken thighs from both sides with the help of meat mallet.",
      "Sprinkle prepared spice mix (reserved seasoning for later use) on both sides, rub evenly & let them rest for 10 minutes.",
      "Add reserved spice mix (1 tbs) in all-purpose flour & mix well.",
      "Coat chicken thighs in dry flour mixture then dip into water then again coat with dry flour mixture.",
      "In a wok, heat cooking oil & fry on medium flame until golden & crispy.",
      "On burger bun, add & spread mayonnaise, iceberg, crispy fried chicken, prepared spicy mayo sauce, prepared cheese patty, spicy mayo sauce, iceberg & pickled jalapenos.",
      "Spread mayonnaise on top bun & flip to make a burger (makes 3).",
      "Serve with French fries & tomato ketchup!",
    ],
  },
};
// ==========================Lunch/Dinner recipies==========================
